// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQZQw3eOnZLFpDO9F6D3SBxoogYsybQ0Y',
    appId: '1:709101583410:web:31590ff8927d9ba252102b',
    messagingSenderId: '709101583410',
    projectId: 'ridingpartner-4dd9e',
    authDomain: 'ridingpartner-4dd9e.firebaseapp.com',
    storageBucket: 'ridingpartner-4dd9e.appspot.com',
    measurementId: 'G-S9FBYX7E8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMXp5uBX4I-lVqeykT9_zmcT3KEVlTgqk',
    appId: '1:709101583410:android:4aa06bf890507d6e52102b',
    messagingSenderId: '709101583410',
    projectId: 'ridingpartner-4dd9e',
    storageBucket: 'ridingpartner-4dd9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx7zSn7x4kVRp_Gs3c0QyxLUg51n0TCgU',
    appId: '1:709101583410:ios:ca20b0623aa9447252102b',
    messagingSenderId: '709101583410',
    projectId: 'ridingpartner-4dd9e',
    storageBucket: 'ridingpartner-4dd9e.appspot.com',
    iosClientId: '709101583410-89lcjpumtpgon28thqls428a4bsgblip.apps.googleusercontent.com',
    iosBundleId: 'com.neighbor.ridingpartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx7zSn7x4kVRp_Gs3c0QyxLUg51n0TCgU',
    appId: '1:709101583410:ios:ef9355ca3641fc2c52102b',
    messagingSenderId: '709101583410',
    projectId: 'ridingpartner-4dd9e',
    storageBucket: 'ridingpartner-4dd9e.appspot.com',
    iosClientId: '709101583410-s90e3a4j7qki02i9b5b08hp7sqb4kkh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridingpartner.RunnerTests',
  );
}
